/* mouse.c generated by valac 0.18.0, the Vala compiler
 * generated from mouse.vala, do not modify */

/* valac --vapidir=./ libsuinput.vapi example/mouse.vala --pkg linux -X -lsuinput*/

#include <glib.h>
#include <glib-object.h>
#include <linux/input.h>
#include <string.h>
#include <linux/uinput.h>
#include "suinput.h"
#include <unistd.h>




gint _vala_main (void);


gint _vala_main (void) {
	gint result = 0;
	gint fd = 0;
	gint* _tmp0_ = NULL;
	gint* btns;
	gint btns_length1;
	gint _btns_size_;
	gint* _tmp1_ = NULL;
	gint* rel_axes;
	gint rel_axes_length1;
	gint _rel_axes_size_;
	gint i = 0;
	struct uinput_user_dev uidev = {0};
	gint _tmp2_ = 0;
	_tmp0_ = g_new0 (gint, 3);
	_tmp0_[0] = BTN_LEFT;
	_tmp0_[1] = BTN_RIGHT;
	_tmp0_[2] = BTN_MIDDLE;
	btns = _tmp0_;
	btns_length1 = 3;
	_btns_size_ = btns_length1;
	_tmp1_ = g_new0 (gint, 3);
	_tmp1_[0] = REL_X;
	_tmp1_[1] = REL_Y;
	_tmp1_[2] = REL_WHEEL;
	rel_axes = _tmp1_;
	rel_axes_length1 = 3;
	_rel_axes_size_ = rel_axes_length1;
	memset (&uidev, 0, sizeof (struct uinput_user_dev));
	memcpy (uidev.name, (gchar*) "libsuinput-example-mouse", 80 * sizeof (gchar));
	_tmp2_ = suinput_open ();
	fd = _tmp2_;
	if (fd == (-1)) {
		g_error ("mouse.vala:19: suinput_open");
	}
	{
		gboolean _tmp3_;
		i = 0;
		_tmp3_ = TRUE;
		while (TRUE) {
			gboolean _tmp4_;
			gint _tmp6_;
			gint _tmp7_;
			gint _tmp8_;
			_tmp4_ = _tmp3_;
			if (!_tmp4_) {
				gint _tmp5_;
				_tmp5_ = i;
				i = _tmp5_ + 1;
			}
			_tmp3_ = FALSE;
			_tmp6_ = i;
			if (!(_tmp6_ < 3)) {
				break;
			}
			_tmp7_ = i;
			_tmp8_ = btns[_tmp7_];
			suinput_enable_event (fd, (guint16) EV_KEY, (guint16) _tmp8_);
		}
	}
	{
		gboolean _tmp9_;
		i = 0;
		_tmp9_ = TRUE;
		while (TRUE) {
			gboolean _tmp10_;
			gint _tmp12_;
			gint _tmp13_;
			gint _tmp14_;
			_tmp10_ = _tmp9_;
			if (!_tmp10_) {
				gint _tmp11_;
				_tmp11_ = i;
				i = _tmp11_ + 1;
			}
			_tmp9_ = FALSE;
			_tmp12_ = i;
			if (!(_tmp12_ < 3)) {
				break;
			}
			_tmp13_ = i;
			_tmp14_ = rel_axes[_tmp13_];
			suinput_enable_event (fd, (guint16) EV_REL, (guint16) _tmp14_);
		}
	}
	suinput_create (fd, &uidev);
	{
		gboolean _tmp15_;
		i = 0;
		_tmp15_ = TRUE;
		while (TRUE) {
			gboolean _tmp16_;
			gint _tmp18_;
			_tmp16_ = _tmp15_;
			if (!_tmp16_) {
				gint _tmp17_;
				_tmp17_ = i;
				i = _tmp17_ + 1;
			}
			_tmp15_ = FALSE;
			_tmp18_ = i;
			if (!(_tmp18_ < 20)) {
				break;
			}
			suinput_emit (fd, (guint16) EV_REL, (guint16) REL_X, (gint32) 5);
			suinput_emit (fd, (guint16) EV_REL, (guint16) REL_Y, (gint32) 5);
			suinput_syn (fd);
			sleep ((guint) 5);
		}
	}
	suinput_emit (fd, EV_KEY, (guint16) BTN_LEFT, (gint32) 1);
	suinput_syn (fd);
	suinput_emit (fd, EV_KEY, (guint16) BTN_LEFT, (gint32) 0);
	suinput_syn (fd);
	suinput_destroy (fd);
	result = 0;
	 (&uidev);
	rel_axes = (g_free (rel_axes), NULL);
	btns = (g_free (btns), NULL);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main ();
}



